name: ğŸ“‹ Quality Checks

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  lint:
    name: ğŸ“‹ Lint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Git clone the repository
        uses: actions/checkout@v5

      - name: ğŸ“¦ Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ§ª Lint
        run: mise lint

  test:
    name: ğŸ“‹ Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Git clone the repository
        uses: actions/checkout@v5

      - name: ğŸ“¦ Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ§ª Lint
        run: mise test

  integration-test:
    name: ğŸ“‹ Integration test
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Git clone the repository
        uses: actions/checkout@v5

      - name: ğŸ“¦ Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start FPM
        run: |
          docker compose up --quiet-pull -d

      - name: Test sidecar
        run: | 
          mise build
          ./bin/skpr-fpm-metrics-adapter-sidecar --port :8080 &
          # Needed because if request comes too early, server hasn't fetched results
          sleep 15
          mise test:integration
